# Generated by Django 5.0.3 on 2024-03-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_products_product_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_created_in', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_value', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('product_description', models.TextField(default='', max_length=200)),
            ],
            options={
                'ordering': ['product_created_in'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
